version: 0.1

environment_variables:
  plaintext:
    BUILD: 'SNAPSHOT'

phases:
  install:
    # Install additional SW not included in the docker image
    commands:
      - 'echo "Here I prepare my platform"'
  pre_build:
    # Prepare for executing the build. Maybe point to your artifactory, npm install, checkout more repos, etc.
    commands:
      - 'echo "Here I prepare my environment"'
      - 'pip install pytest'
      - 'mkdir -p build'
  build:
    # Compile, test, bundle, whatever produces deployable artifacts
    commands:
      - 'echo "Here I build and test things"'
      - 'BUILD=${CODEBUILD_BUILD_ID} python make.py'
      - 'echo "Here I create or copy deployment instructions"'
      - 'cp -r deploy build'
  post_build:
    # package up your deployables, generate deploy scripts, etc.
    commands:
      - 'echo "Here I package stuff for distribution"'
      - 'mkdir -p dist'
      - 'echo ${CODEBUILD_BUILD_ID} > dist/manifest.txt'
      - 'cp appspec.yml dist'
      - 'cp -r build dist'

artifacts:
  files:
    - 'dist/**/*'
  discard-paths: false
