---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'CodePipeline Demo'

Parameters:
  GitHubOAuthToken:
    Type: String
    NoEcho: True
  TestDeploymentGroup:
    Type: 'String'
    Description: 'Test Deployment Group Name'
  ProdDeploymentGroup:
    Type: 'String'
    Description: 'Prod Deployment Group Name'
  ApprovalNotificationArn:
    Type: 'String'
    Description: 'Notification ARN for Prod approvals'

Resources:
  DemoPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Location: !ImportValue CodePipelineArtifactBucket
        Type: S3
      RoleArn: !Sub '${DemoPipelineIAMRole.Arn}'
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: mccormickmichael
                Repo: codepipeline-demo-one
                Branch: master
                OAuthToken: !Ref GitHubOAuthToken
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref DemoCodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildProductArtifact
        - Name: Deploy
          Actions:
            - Name: Deploy to Test
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              Configuration:
                ApplicationName: !Ref DemoApplicationTest
                DeploymentGroupName: !Ref DemoDeploymentGroupTest
              InputArtifacts:
                - Name: BuildProductArtifact
              RunOrder: 1
        - Name: Approve
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              Configuration:
                NotificationArn: !Ref ApprovalNotificationArn
                CustomData: 'Look at this!'
        - Name: Deploy
          Actions:
            - Name: Deploy to Prod
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              Configuration:
                ApplicationName: !Ref DemoApplicationProd
                DeploymentGroupName: !Ref DemoDeploymentGroupProd
              InputArtifacts:
                - Name: BuildProductArtifact
              RunOrder: 1
              
  DemoPipelineIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: >
        {"Version":"2012-10-17","Statement":{"Effect":"Allow","Principal":{"Service":"codepipeline.amazonaws.com"},"Action":"sts:AssumeRole"}}
      ManagedPolicyArns:
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/machine-deploy-s3'
        - 'arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess'
        - 'arn:aws:iam::aws:policy/AWSCodeDeployFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'

# CodeBuild Stage
  DemoCodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: 'CodePipelineDemoCodeBuild'
      Description: 'Code Pipeline CodeBuild project'
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/eb-python-2.7-amazonlinux-64:2.1.6'
        Type: LINUX_CONTAINER
      TimeoutInMinutes: 10
      Tags: []
  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: >
        {"Version":"2012-10-17","Statement":{"Effect":"Allow","Principal":{"Service":"codebuild.amazonaws.com"},"Action":"sts:AssumeRole"}}
      ManagedPolicyArns:
        # These could(should?) be custom policies
        - 'arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/machine-deploy-s3'

# CodeDeploy Test Stage
  DemoApplicationTest:
    Type: 'AWS::CodeDeploy::Application'
  DemoDeploymentGroupTest:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName: !Ref DemoApplicationTest
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      Ec2TagFilters:
        - Type: KEY_AND_VALUE
          Key: DeploymentGroup
          Value: !Ref TestDeploymentGroup
      ServiceRoleArn: !Sub '${DemoIAMRole.Arn}'
      
  DemoApplicationProd:
    Type: 'AWS::CodeDeploy::Application'
  DemoDeploymentGroupProd:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName: !Ref DemoApplicationProd
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      Ec2TagFilters:
        - Type: KEY_AND_VALUE
          Key: DeploymentGroup
          Value: !Ref ProdDeploymentGroup
      ServiceRoleArn: !Sub '${DemoIAMRole.Arn}'
      
  DemoIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: >
        {"Version":"2012-10-17","Statement":{"Effect":"Allow","Principal":{"Service":"codedeploy.amazonaws.com"},"Action":"sts:AssumeRole"}}
      Path: '/'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole'


  # DemoLambdaTrigger: BLAH

